# Generated by Django 5.0.7 on 2026-05-25 16:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('country', models.CharField(default='IN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SourceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP fuel/procurement'), ('utility', 'Utility electricity'), ('travel', 'Corporate travel')], max_length=20)),
                ('source_name', models.CharField(max_length=160)),
                ('ingestion_mode', models.CharField(max_length=80)),
                ('source_reference', models.CharField(max_length=160)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=120)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('category', models.CharField(max_length=80)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('description', models.CharField(max_length=240)),
                ('raw_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('raw_unit', models.CharField(max_length=24)),
                ('normalized_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('normalized_unit', models.CharField(max_length=24)),
                ('emission_factor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('co2e_kg', models.DecimalField(decimal_places=3, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for audit')], default='pending', max_length=20)),
                ('suspicion_reason', models.TextField(blank=True)),
                ('raw_payload', models.JSONField(default=dict)),
                ('edited_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=120)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.facility')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ingest.sourcebatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.tenant')),
            ],
            options={
                'ordering': ('-activity_date', 'external_id'),
                'unique_together': {('tenant', 'batch', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=40)),
                ('note', models.TextField(blank=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ingest.emissionactivity')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='sourcebatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.tenant'),
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ingest.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('tenant', 'code')},
        ),
    ]
